let af_data = {
  "direct_trackings": [{
    "id": "784adc2f7f634d6ca08d9fef8e2cd504",
    "tracking": {
      "id": "0acc9b08ca944eb98417ef0902ac1ed6",
      "checkpoints": [{
        "slug": "usps",
        "created_at": "2021-08-04T08:49:09.097Z",
        "message": "Picked Up by Shipping Partner, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "OAK CREEK",
          "state": "WI",
          "postal_code": "53154",
          "country": "USA",
          "type": null,
          "raw_location": "OAK CREEK, WI, 53154, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-08-03T05:55:00"
      }, {
        "slug": "usps",
        "created_at": "2021-08-04T08:49:09.097Z",
        "message": "Departed Shipping Partner Facility, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "OAK CREEK",
          "state": "WI",
          "postal_code": "53154",
          "country": "USA",
          "type": null,
          "raw_location": "OAK CREEK, WI, 53154, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-08-03T08:07:00"
      }, {
        "slug": "usps",
        "created_at": "2021-08-04T08:49:09.097Z",
        "message": "Departed Shipping Partner Facility, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "LOCKPORT",
          "state": "IL",
          "postal_code": "60441",
          "country": "USA",
          "type": null,
          "raw_location": "LOCKPORT, IL, 60441, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-08-03T18:10:00"
      }, {
        "slug": "usps",
        "created_at": "2021-08-05T08:47:44.126Z",
        "message": "Departed Shipping Partner Facility, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "BALTIMORE",
          "state": "MD",
          "postal_code": "21224",
          "country": "USA",
          "type": null,
          "raw_location": "BALTIMORE, MD, 21224, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-08-05T00:04:00"
      }],
      "estimated_delivery_date": null,
      "signature_name": null,
      "slug": "usps",
      "courier": {
        "slug": "usps",
        "name": "USPS",
        "phone": "+1 (800) 275-8777",
        "other_name": "United States Postal Service",
        "default_language": "en",
        "global_branch_phones": null,
        "required_fields": [],
        "optional_fields": [],
        "service_from_country_iso3": ["USA"],
        "support_languages": ["en"],
        "web_url": "https://www.usps.com"
      },
      "latest_status": "InTransit",
      "tracking_number": "9361289738009091755413",
      "courier_tracking_link": "https://tools.usps.com/go/TrackConfirmAction?tLabels=9361289738009091755413",
      "courier_redirect_link": "https://tools.usps.com/go/TrackConfirmAction?tRef=fullpage&tLc=2&text28777=&tLabels=9361289738009091755413%2C",
      "courier_origin_address": {
        "contact_name": null,
        "company_name": null,
        "street_1": null,
        "street_2": null,
        "street_3": null,
        "city": "OAK CREEK",
        "state": "WI",
        "postal_code": "53154",
        "country": "USA",
        "type": null,
        "raw_location": "OAK CREEK, WI, 53154, USA, United States",
        "coordinates": null
      },
      "courier_destination_address": {
        "contact_name": null,
        "company_name": null,
        "street_1": null,
        "street_2": null,
        "street_3": null,
        "city": "BROOKLYN",
        "state": "NY",
        "postal_code": "11233",
        "country": "USA",
        "type": null,
        "raw_location": "BROOKLYN, NY, 11233, USA, United States",
        "coordinates": null
      },
      "service_type_name": "Parcel Select",
      "delivery_days": 3,
      "delivery_date": null,
      "courier_pickup_location": null,
      "updated_at": "2021-08-05T08:47:44.126Z"
    },
    "slug": "usps",
    "tracking_number": "9361289738009091755413",
    "additional_fields": {},
    "is_instant_track": true,
    "detected_slugs": ["usps", "delnext", "omniparcel", "dhl-global-mail", "brt-it-sender-ref"],
    "error_code": null
  }, {
    "id": "bbe5d95f05bf4310951a28fc25d64e59",
    "tracking": {
      "id": "5665bd9347ff4a50871f2e4786b9863b",
      "checkpoints": [{
        "slug": "usps",
        "created_at": "2021-07-23T08:42:47.746Z",
        "message": "Picked Up by Shipping Partner, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "BREINIGSVILLE",
          "state": "PA",
          "postal_code": "18031",
          "country": "USA",
          "type": null,
          "raw_location": "BREINIGSVILLE, PA, 18031, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-07-20T14:07:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-23T08:42:47.746Z",
        "message": "Departed Shipping Partner Facility, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "BREINIGSVILLE",
          "state": "PA",
          "postal_code": "18031",
          "country": "USA",
          "type": null,
          "raw_location": "BREINIGSVILLE, PA, 18031, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-07-21T09:25:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-23T08:42:47.746Z",
        "message": "Departed Shipping Partner Facility, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "TETERBORO",
          "state": "NJ",
          "postal_code": "07608",
          "country": "USA",
          "type": null,
          "raw_location": "TETERBORO, NJ, 07608, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-07-21T16:46:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-23T08:42:47.746Z",
        "message": "Departed Shipping Partner Facility, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "HEBRON",
          "state": "KY",
          "postal_code": "41048",
          "country": "USA",
          "type": null,
          "raw_location": "HEBRON, KY, 41048, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-07-22T21:08:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-24T08:04:59.652Z",
        "message": "Departed Shipping Partner Facility, USPS Awaiting Item",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "ATLANTA",
          "state": "GA",
          "postal_code": "30349",
          "country": "USA",
          "type": null,
          "raw_location": "ATLANTA, GA, 30349, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-07-24T00:39:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-24T09:39:50.912Z",
        "message": "Acceptance",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "CUMMING",
          "state": "GA",
          "postal_code": "30040",
          "country": "USA",
          "type": null,
          "raw_location": "CUMMING, GA, 30040, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-07-24T04:36:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-24T10:40:00.295Z",
        "message": "Arrived at Post Office",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "CUMMING",
          "state": "GA",
          "postal_code": "30040",
          "country": "USA",
          "type": null,
          "raw_location": "CUMMING, GA, 30040, USA, United States",
          "coordinates": null
        },
        "status": "InTransit",
        "date_time": "2021-07-24T06:16:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-24T10:40:00.295Z",
        "message": "Out for Delivery, Expected Delivery by 9:00pm",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "CUMMING",
          "state": "GA",
          "postal_code": "30040",
          "country": "USA",
          "type": null,
          "raw_location": "CUMMING, GA, 30040, USA, United States",
          "coordinates": null
        },
        "status": "OutForDelivery",
        "date_time": "2021-07-24T06:27:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-24T14:12:42.690Z",
        "message": "Out for Delivery",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "CUMMING",
          "state": "GA",
          "postal_code": "30040",
          "country": "USA",
          "type": null,
          "raw_location": "CUMMING, GA, 30040, USA, United States",
          "coordinates": null
        },
        "status": "OutForDelivery",
        "date_time": "2021-07-24T06:27:00"
      }, {
        "slug": "usps",
        "created_at": "2021-07-24T14:12:42.690Z",
        "message": "Delivered, In/At Mailbox",
        "address": {
          "contact_name": null,
          "company_name": null,
          "street_1": null,
          "street_2": null,
          "street_3": null,
          "city": "CUMMING",
          "state": "GA",
          "postal_code": "30040",
          "country": "USA",
          "type": null,
          "raw_location": "CUMMING, GA, 30040, USA, United States",
          "coordinates": null
        },
        "status": "Delivered",
        "date_time": "2021-07-24T10:04:00"
      }],
      "estimated_delivery_date": "2021-07-24",
      "signature_name": null,
      "slug": "usps",
      "courier": {
        "slug": "usps",
        "name": "USPS",
        "phone": "+1 (800) 275-8777",
        "other_name": "United States Postal Service",
        "default_language": "en",
        "global_branch_phones": null,
        "required_fields": [],
        "optional_fields": [],
        "service_from_country_iso3": ["USA"],
        "support_languages": ["en"],
        "web_url": "https://www.usps.com"
      },
      "latest_status": "Delivered",
      "tracking_number": "9374889675091115019951",
      "courier_tracking_link": "https://tools.usps.com/go/TrackConfirmAction?tLabels=9374889675091115019951",
      "courier_redirect_link": "https://tools.usps.com/go/TrackConfirmAction?tRef=fullpage&tLc=2&text28777=&tLabels=9374889675091115019951%2C",
      "courier_origin_address": {
        "contact_name": null,
        "company_name": null,
        "street_1": null,
        "street_2": null,
        "street_3": null,
        "city": "CUMMING",
        "state": "GA",
        "postal_code": "30040",
        "country": "USA",
        "type": null,
        "raw_location": "CUMMING, GA, 30040, USA, United States",
        "coordinates": null
      },
      "courier_destination_address": {
        "contact_name": null,
        "company_name": null,
        "street_1": null,
        "street_2": null,
        "street_3": null,
        "city": "CUMMING",
        "state": "GA",
        "postal_code": "30040",
        "country": "USA",
        "type": null,
        "raw_location": "CUMMING, GA, 30040, USA, United States",
        "coordinates": null
      },
      "service_type_name": "Parcel Select Lightweight",
      "delivery_days": 5,
      "delivery_date": "2021-07-24T10:04:00",
      "courier_pickup_location": null,
      "updated_at": "2021-07-24T14:12:42.690Z"
    },
    "slug": "usps",
    "tracking_number": "9374889675091115019951",
    "additional_fields": {},
    "is_instant_track": false,
    "detected_slugs": ["usps", "delnext", "dhl-global-mail", "ec-firstclass", "brt-it-sender-ref"],
    "error_code": null
  }],
  "slugs": []
}